/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package foxxoshell

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting)
    }
}
